v = input('Digite algo: ')
print('---------------------------')
print('Qual seu tipo? ', type(v))
print('---------------------------')
print('É alpha númerico (a-z)(0-9)? ', v.isalnum())
print('É númerico (0-9)? ', v.isnumeric())
print('É alpha (a-z)? ', v.isalpha())
print('É decimal (0-9)? ', v.isdecimal())
print('É minusculo (aaa)? ', v.islower())
print('É maiusculo (AAA)? ', v.isupper())
print('É titulo (Inicio Com Maiusculas)? ', v.istitle())
print('É espaço? ', v.isspace())
print('É digito? ', v.isdigit())
print('É identifier? ', v.isidentifier())
print('É capitalizado? ', v.capitalize())
print('É ascii? ', v.isascii())